# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: M Durães
email: mduraes1994@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Um blog sobre tecnologia, seja bem vindo
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mateusduraes.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: mateusduraes

# Build settings
markdown: kramdown
# permalink: /:categories/:year/:month/:day/:title
# permalink: /:year/:month/:day/:title
permalink: /:title/