title: Mateus Durães - Desenvolvedor Fullstack
description: > # this means to ignore newlines until "baseurl:"
  Desenvolvedor Fullstack JavaScript, trabalhando com Angular, Ionic, NodeJs e Firebase.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mateusduraes.com.br" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Mateus Durães # add your name
author-img: mateus.jpg # add your photo
about-author: Desenvolvedor Fullstack JavaScript, trabalhando com Angular, Ionic, NodeJs e Firebase. # add description
twitter: # add your Twitter handle
facebook: # add your Facebook handle
github: mateusduraes # add your Github handle
linkedin: https://www.linkedin.com/in/mateus-ferreira-durães-79b584122 # add your Linkedin handle
email: mduraes1994@gmail.com # add your Email address

# Disqus
discus-identifier: mateusduraes-github-io # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate

# Gems
plugins: [jekyll-paginate, jemoji, github-pages]

paginate: 4
paginate_path: "/page/:num"


exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
